INSERT INTO code_groups (group_id, group_name, enabled, created_at) VALUES
  ('NEWS_CATEGORY', '뉴스 카테고리', true, CURRENT_TIMESTAMP),
  ('NEWS_IMPACT', '관련 종목 영향', true, CURRENT_TIMESTAMP),
  ('STOCK_MARKET', '주식 시장', true, CURRENT_TIMESTAMP),
  ('STOCK_SECTOR', '주식 업종', true, CURRENT_TIMESTAMP),
  ('TRADE_TYPE', '거래 유형', true, CURRENT_TIMESTAMP),
  ('JOURNAL_STATUS', '주식일지 상태', true, CURRENT_TIMESTAMP),
  ('AI_SENTIMENT', 'AI 신호', true, CURRENT_TIMESTAMP),
  ('USER_STATUS', '회원 상태', true, CURRENT_TIMESTAMP),
  ('USER_PROVIDER', '가입 경로', true, CURRENT_TIMESTAMP);

INSERT INTO codes (code_value, code_name, group_id, sort_order, enabled, created_at) VALUES
  ('DOMESTIC', '국내', 'NEWS_CATEGORY', 1, true, CURRENT_TIMESTAMP),
  ('OVERSEAS', '해외', 'NEWS_CATEGORY', 2, true, CURRENT_TIMESTAMP),

  ('BENEFIT', '동반 수혜', 'NEWS_IMPACT', 1, true, CURRENT_TIMESTAMP),
  ('LIMITED', '제한적 영향', 'NEWS_IMPACT', 2, true, CURRENT_TIMESTAMP),
  ('ADVERSE', '동반 약세', 'NEWS_IMPACT', 3, true, CURRENT_TIMESTAMP),

  ('KOSPI', 'KOSPI', 'STOCK_MARKET', 1, true, CURRENT_TIMESTAMP),
  ('KOSDAQ', 'KOSDAQ', 'STOCK_MARKET', 2, true, CURRENT_TIMESTAMP),
  ('NASDAQ', 'NASDAQ', 'STOCK_MARKET', 3, true, CURRENT_TIMESTAMP),

  ('ELECTRONICS', '전기전자', 'STOCK_SECTOR', 1, true, CURRENT_TIMESTAMP),
  ('CHEMICAL', '화학', 'STOCK_SECTOR', 2, true, CURRENT_TIMESTAMP),
  ('TRANSPORT_EQUIPMENT', '운수장비', 'STOCK_SECTOR', 3, true, CURRENT_TIMESTAMP),
  ('PHARMACEUTICAL', '의약품', 'STOCK_SECTOR', 4, true, CURRENT_TIMESTAMP),
  ('FINANCIAL', '금융업', 'STOCK_SECTOR', 5, true, CURRENT_TIMESTAMP),
  ('STEEL_METAL', '철강금속', 'STOCK_SECTOR', 6, true, CURRENT_TIMESTAMP),
  ('CONSTRUCTION', '건설업', 'STOCK_SECTOR', 7, true, CURRENT_TIMESTAMP),
  ('RETAIL', '유통업', 'STOCK_SECTOR', 8, true, CURRENT_TIMESTAMP),
  ('FOOD_BEVERAGE', '음식료품', 'STOCK_SECTOR', 9, true, CURRENT_TIMESTAMP),
  ('TEXTILE_APPAREL', '섬유의복', 'STOCK_SECTOR', 10, true, CURRENT_TIMESTAMP),
  ('PAPER_WOOD', '종이목재', 'STOCK_SECTOR', 11, true, CURRENT_TIMESTAMP),
  ('NON_METALLIC_MINERAL', '비금속광물', 'STOCK_SECTOR', 12, true, CURRENT_TIMESTAMP),
  ('MACHINERY', '기계', 'STOCK_SECTOR', 13, true, CURRENT_TIMESTAMP),
  ('MEDICAL_PRECISION', '의료정밀', 'STOCK_SECTOR', 14, true, CURRENT_TIMESTAMP),
  ('ELECTRIC_GAS', '전기가스업', 'STOCK_SECTOR', 15, true, CURRENT_TIMESTAMP),
  ('TRANSPORT_STORAGE', '운수창고업', 'STOCK_SECTOR', 16, true, CURRENT_TIMESTAMP),
  ('TELECOMMUNICATION', '통신업', 'STOCK_SECTOR', 17, true, CURRENT_TIMESTAMP),
  ('SERVICE', '서비스업', 'STOCK_SECTOR', 18, true, CURRENT_TIMESTAMP),
  ('BANK', '은행', 'STOCK_SECTOR', 19, true, CURRENT_TIMESTAMP),
  ('SECURITIES', '증권', 'STOCK_SECTOR', 20, true, CURRENT_TIMESTAMP),
  ('INSURANCE', '보험', 'STOCK_SECTOR', 21, true, CURRENT_TIMESTAMP),

  ('BUY', '매수', 'TRADE_TYPE', 1, true, CURRENT_TIMESTAMP),
  ('SELL', '매도', 'TRADE_TYPE', 2, true, CURRENT_TIMESTAMP),

  ('DONE', 'AI 분석 완료', 'JOURNAL_STATUS', 1, true, CURRENT_TIMESTAMP),
  ('PENDING', 'AI 분석 중', 'JOURNAL_STATUS', 2, true, CURRENT_TIMESTAMP),
  ('STANDBY', '분석 대기', 'JOURNAL_STATUS', 3, true, CURRENT_TIMESTAMP),

  ('POSITIVE', '긍정', 'AI_SENTIMENT', 1, true, CURRENT_TIMESTAMP),
  ('NEUTRAL', '중립', 'AI_SENTIMENT', 2, true, CURRENT_TIMESTAMP),
  ('NEGATIVE', '부정', 'AI_SENTIMENT', 3, true, CURRENT_TIMESTAMP),

  ('ACTIVE', '정상', 'USER_STATUS', 1, true, CURRENT_TIMESTAMP),
  ('WITHDRAWN', '탈퇴', 'USER_STATUS', 2, true, CURRENT_TIMESTAMP),

  ('LOCAL', '자체 가입', 'USER_PROVIDER', 1, true, CURRENT_TIMESTAMP),
  ('GOOGLE', '구글 가입', 'USER_PROVIDER', 2, true, CURRENT_TIMESTAMP);
